### PR TITLE
Bump to 0.5.0.

### PR DESCRIPTION
**Pull request by adleong**

### CODE REVIEW

**Comment by olix0r** [comment]
should this also add calls to `kubectl proxy` for the namerd config?

**Comment by adleong** [comment]
It's already there: https://github.com/BuoyantIO/linkerd-examples/pull/14/files#diff-f4e146ea786cfa276ff176b9e093d796R40

**Comment by olix0r** [comment]
:star: doh

**Comment by klingerf** [comment]
⭐ 🐌

**Pull request merged**
